name: 'Build'

on:
  workflow_dispatch:
    inputs:
      kernel_ver:
        description: 'WSL2 kernel version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download WSL2 kernel source'
        run: |
          curl https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-${{ inputs.kernel_ver }}.tar.gz -O wsl2.tar.gz
